# Generated by Django 5.2.8 on 2026-02-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_stock_purchase_quantity_purchase_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'محصولات الکترونیک'), ('accessories', 'لوازم جانبی الکترونیک')], default='electronics', max_length=20),
        ),
    ]
