# Generated by Django 5.2.8 on 2026-02-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='address',
            field=models.TextField(blank=True, help_text='Shop address', null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number with country code (e.g., +989123456789)', max_length=20, null=True),
        ),
    ]
