# Generated by Django 5.2.8 on 2026-10-04 20:42

import unicodedata

from django.apps.registry import Apps
from django.contrib.auth.hashers import identify_hasher, make_password
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def hash_existing_answers(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Normalize and hash legacy answers; blank answers can never unlock recovery."""
    alias = schema_editor.connection.alias
    for model_name in ("Customer", "ShopOwner"):
        model = apps.get_model("accounts", model_name)
        accounts = model.objects.using(alias)
        for account in accounts.all().iterator():
            updates = {}
            for field in ("security_answer1", "security_answer2"):
                value = getattr(account, field)
                if value:
                    try:
                        identify_hasher(value)
                    except ValueError:
                        pass
                    else:
                        continue
                normalized = (
                    unicodedata.normalize("NFKC", value or "").strip().casefold()
                )
                updates[field] = make_password(normalized or None)
            if updates:
                accounts.filter(pk=account.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_hash_shop_owner_passwords"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="recovery_failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="recovery_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shopowner",
            name="recovery_failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shopowner",
            name="recovery_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(hash_existing_answers, migrations.RunPython.noop),
    ]
